// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenVanHoang_231220789_De02.Models;

#nullable disable

namespace NguyenVanHoang_231220789_De02.Migrations
{
    [DbContext(typeof(NvhDbContext))]
    [Migration("20251024032524_InitNvhCatalog")]
    partial class InitNvhCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NguyenVanHoang_231220789_De02.Models.NvhCatalog", b =>
                {
                    b.Property<int>("nvhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nvhId"));

                    b.Property<bool>("nvhCateActive")
                        .HasColumnType("bit");

                    b.Property<string>("nvhCateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("nvhCatePrice")
                        .HasColumnType("int");

                    b.Property<int>("nvhCateQty")
                        .HasColumnType("int");

                    b.Property<string>("nvhPicture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nvhId");

                    b.ToTable("NvhCatalog");
                });
#pragma warning restore 612, 618
        }
    }
}
